use rand::seq::SliceRandom;
use rand::thread_rng;
use std::{thread, time::Duration, process::Command};
use urlencoding::encode;

fn escape_cmd_ampersand(url: &str) -> String {
    url.replace("&", "^&")
}

fn main() {
    let search_terms = vec![
        "resume examples",
        "cover letter templates",
        "job interview tips",
        "time management techniques",
        "study hacks",
        "coding tutorials",
        "learn Python",
        "graphic design tips",
        "photo editing software",
        "video editing apps",
        "gaming news",
        "PC build guide",
        "laptop buying guide",
        "smart home gadgets",
        "budgeting tips",
        "personal finance advice",
        "credit card reviews",
        "investment strategies",
        "retirement planning",
        "insurance quotes",
        "mortgage calculator",
        "real estate listings",
        "home decor ideas",
        "minimalist lifestyle",
        "eco-friendly products",
        "healthy recipes",
        "vegetarian meals",
        "vegan snacks",
        "gluten-free desserts",
        "yoga for beginners",
        "meditation techniques",
        "mental health resources",
        "therapy options",
        "relationship advice",
        "parenting tips",
        "baby names",
        "wedding planning",
        "gift ideas",
        "birthday party themes",
        "holiday decorations",
        "Christmas gift guide",
        "valentine’s day crafts",
        "school supplies list",
        "college application tips",
        "scholarship search",
        "SAT practice questions",
        "essay writing tips",
        "grammar checker",
        "book recommendations",
        "best podcasts 2025",
        "music playlist ideas",
        "learn guitar",
        "piano tutorials",
        "language learning apps",
        "history facts",
        "science experiments",
        "math help",
        "algebra formulas",
        "physics equations",
        "chemistry periodic table",
        "biology diagrams",
        "geography quiz",
        "politics news",
        "government updates",
        "climate change articles",
        "environmental issues",
        "wildlife conservation",
        "space exploration",
        "NASA updates",
        "AI trends",
        "machine learning basics",
        "blockchain explained",
        "crypto news",
        "Bitcoin price",
        "Ethereum forecast",
        "NFT marketplaces",
        "online security tips",
        "password manager apps",
        "VPN comparison",
        "privacy tools",
        "data backup solutions",
        "cloud storage reviews",
        "email tips",
        "calendar apps",
        "to-do list software",
        "note taking tools",
        "team collaboration platforms",
        "remote work software",
        "productivity hacks",
        "startup ideas",
        "business plans",
        "entrepreneur resources",
        "marketing tools",
        "SEO basics",
        "Google Analytics guide",
        "ecommerce tips",
        "shopify tutorial",
        "dropshipping ideas",
        "customer service strategies",
        "branding tips",
        "logo design inspiration",
        "color theory guide",
        "typography resources",
        "interior design trends",
        "fashion ideas",
        "makeup tutorials",
        "skincare routines",
        "hairstyle ideas",
        "nail art designs",
        "tattoo inspiration",
        "piercing aftercare",
        "fitness tracker reviews",
        "workout apps",
        "gym exercises",
        "running techniques",
        "cycling routes",
        "hiking gear",
        "camping checklist",
        "fishing tips",
        "hunting regulations",
        "sports news",
        "football scores",
        "basketball highlights",
        "soccer match results",
        "tennis updates",
        "olympic games schedule",
        "streaming services list",
        "Netflix recommendations",
        "Hulu vs Disney+",
        "TV show reviews",
        "movie trailers",
        "celebrity gossip",
        "red carpet photos",
        "award show winners",
        "pet care tips",
        "dog training tricks",
        "cat breeds",
        "bird feeding guide",
        "aquarium maintenance",
        "reptile facts",
        "horseback riding tips",
        "gardening guide",
        "plant care schedule",
        "composting tips",
        "urban farming",
        "cooking classes",
        "baking recipes",
        "meal prep ideas",
        "kitchen gadgets",
        "barbecue tips",
        "wine pairing chart",
        "coffee brewing methods",
        "tea varieties",
        "cocktail recipes",
        "bartending techniques",
        "holiday travel tips",
        "road trip planner",
        "flight status updates",
        "hotel booking sites",
        "cruise vacation deals",
        "passport renewal steps",
        "visa requirements",
        "embassy locator",
        "cultural etiquette",
        "photography tips",
        "camera reviews",
        "lens comparison",
        "photo editing tips",
        "art inspiration",
        "drawing tutorials",
        "painting techniques",
        "sculpting ideas",
        "craft projects",
        "sewing patterns",
        "knitting for beginners",
        "woodworking plans",
        "3D printing guide",
        "electronics repair help",
        "Arduino projects",
        "Raspberry Pi tutorials",
        "home automation setup",
        "drone flying tips",
        "robotics for kids",
        "STEM activities",
        "career change advice",
        "personal growth tips",
        "goal setting strategies",
        "daily affirmations",
        "journaling prompts",
        "motivation quotes",
        "self-help books",
        "mindfulness practices",
        "confidence building tips",
        "leadership skills",
        "public speaking tips",
        "conflict resolution methods",
        "team building activities",
        "networking advice",
        "professional development",
        "conference schedules",
        "industry trends",
        "market analysis",
        "consumer behavior",
        "brand loyalty",
        "sales techniques",
        "negotiation skills",
        "pricing strategies",
        "product launch steps",
        "feedback collection methods",
        "customer satisfaction survey",
        "business ethics",
        "corporate responsibility",
        "remote team management",
        "hybrid work strategies",
        "digital transformation",
        "supply chain logistics",
        "manufacturing processes",
       "quality control",
       "risk management",
       "legal advice",
       "contract templates",
       "tax filing tips",
       "audit checklist",
       "compliance standards",
       "data protection policies",
       "HR best practices",
       "employee onboarding",
       "benefits packages",
       "diversity and inclusion",
       "wellness programs",
       "office ergonomics",
       "safety training",
       "time off policy",
       "vacation planning",
       "employee recognition ideas",
       "team motivation",
       "exit interview questions",
       "performance review tips",
       "modern resume formats",
        "creative cover letter ideas",
        "interview preparation checklist",
        "daily productivity routines",
        "revision techniques for exams",
        "beginner programming guides",
        "intro to Python scripting",
        "user interface design principles",
        "best free photo editors",
        "top mobile video editors",
        "latest in gaming industry",
        "how to build a gaming PC",
        "ultrabook comparison chart",
        "smart device recommendations",
        "how to save money monthly",
        "financial planning tools",
        "best cashback credit cards",
        "ways to grow your savings",
        "how to plan for retirement",
        "compare insurance providers",
        "loan repayment calculators",
        "houses for sale near me",
        "interior design inspiration",
        "simple living guide",
        "zero waste product list",
        "quick healthy meals",
        "plant-based dinner ideas",
        "high-protein vegan snacks",
        "wheat-free dessert options",
        "intro to yoga poses",
        "guided meditation routines",
        "mental wellness apps",
        "finding a counselor",
        "dating and communication tips",
        "raising toddlers advice",
        "popular baby name trends",
        "event planning checklist",
        "unique gift suggestions",
        "children’s party ideas",
        "seasonal home decorating tips",
        "holiday shopping guide",
        "romantic DIY crafts",
        "back to school checklist",
        "university admission help",
        "find college scholarships",
        "free SAT practice tests",
        "academic writing guide",
        "spelling and grammar tools",
        "fiction book must-reads",
        "top podcast episodes",
        "custom music mix ideas",
        "acoustic guitar lessons",
        "learn piano chords",
        "top-rated language apps",
        "important historical events",
        "fun science activities",
        "math problem-solving tricks",
        "key algebra rules",
        "basic physics concepts",
        "element chart facts",
        "anatomy chart reference",
        "geography trivia questions",
        "government policy updates",
        "current political debates",
        "climate reports 2025",
        "green tech solutions",
        "endangered species facts",
        "astronomy discoveries",
        "space agency reports",
        "AI developments this year",
        "intro to neural networks",
        "how blockchain works",
        "crypto market trends",
        "live Bitcoin tracker",
        "Ethereum news today",
        "NFT trading platforms",
        "protecting online privacy",
        "best secure password apps",
        "VPN tools ranked",
        "cybersecurity utilities",
        "how to back up data",
        "top cloud platforms",
        "professional email habits",
        "smart calendar systems",
        "digital checklist apps",
        "organization tools for notes",
        "apps for remote teams",
        "virtual office tools",
        "life productivity methods",
        "new venture ideas",
        "startup pitch templates",
        "resources for founders",
        "advertising software list",
        "SEO tutorial for beginners",
        "Google data tools",
        "running an online store",
        "Shopify setup instructions",
        "top dropship suppliers",
        "handling customer complaints",
        "brand identity creation",
        "modern logo concepts",
        "design with color psychology",
        "typeface usage tips",
        "2025 decor trends",
        "seasonal fashion previews",
        "cosmetic step-by-step",
        "how to manage skincare",
        "simple hairdos",
        "nail polish patterns",
        "tattoo style gallery",
        "how to clean piercings",
        "fitness gadget comparison",
        "home workout platforms",
        "exercise plans for strength",
        "jogging posture tips",
        "bike route maps",
        "checklist for hikers",
        "camping setup guide",
        "angler's starter kit",
        "2025 hunting rules",
        "major sports headlines",
        "latest Premier League scores",
        "NBA best plays",
        "FIFA results roundup",
        "tennis match recaps",
        "international games timeline",
        "streaming app reviews",
        "best series on Netflix",
        "compare Hulu and Disney",
        "TV drama evaluations",
        "upcoming movie previews",
        "celebrity interviews",
        "event photo galleries",
        "award show highlights",
        "animal health advice",
        "obedience training methods",
        "domestic cat types",
        "feeding wild birds",
        "fish tank upkeep",
        "reptile care tips",
        "equestrian basics",
        "how to start gardening",
        "houseplant maintenance",
        "organic composting steps",
        "city farming ideas",
        "culinary skill classes",
        "new dessert ideas",
        "weekly meal plans",
        "best kitchen tools",
        "grill preparation tips",
        "wine with meals",
        "home barista methods",
        "tea flavor profiles",
        "mix drink instructions",
        "bartender training guide",
        "travel tips for holidays",
        "long road trip plan",
        "real-time flight tracking",
        "booking engines ranked",
        "cruise discount alerts",
        "renew your passport guide",
        "international visa info",
        "find nearby consulates",
        "travel etiquette by region",
        "pro photography tricks",
        "camera model guide",
        "compare photo lenses",
        "edit images like a pro",
        "creative art ideas",
        "learn to sketch",
        "paint like a pro",
        "modeling with clay",
        "DIY craft tutorials",
        "how to sew garments",
        "basic knitting guide",
        "furniture build diagrams",
        "intro to 3D modeling",
        "fixing electronics at home",
        "microcontroller projects",
        "Pi-based automation tasks",
        "smart home integrations",
        "beginner drone guide",
        "robot kits for children",
        "engineering games",
        "job switch planning",
        "self-development habits",
        "how to set achievable goals",
        "morning affirmations",
        "daily journal starters",
        "quotes for focus",
        "psychology books to read",
        "living in the present",
        "boosting self-esteem",
        "managing teams effectively",
        "presentation skills",
        "solving team disputes",
        "workplace bonding ideas",
        "how to build a network",
        "career advancement tools",
        "event calendar 2025",
        "tech industry outlook",
        "economic forecast",
        "how buyers behave",
        "building customer loyalty",
        "ways to close sales",
        "bargaining strategies",
        "pricing model templates",
        "checklist for product launch",
        "how to gather user feedback",
        "client review form examples",
        "code of business conduct",
        "sustainability goals",
        "managing remote employees",
        "flexible work policies",
        "digitizing your business",
        "logistics coordination tips",
        "factory operation stages",
        "how to buy a business",
        "outer wilds best moments",
    ];

    let mut rng = thread_rng();
    let selected: Vec<_> = search_terms
        .choose_multiple(&mut rng, 30) //pick 30 random items
        .cloned()
        .collect();

        for term in selected {
            let query = encode(&term); //encode term so it can be used safely in url
            let raw_url = format!("https://www.bing.com/search?q={}&form=TSASDS", query);
    
            // Escape & for Windows CMD shell
            let cmd_url = escape_cmd_ampersand(&raw_url);
    
            let _ = Command::new("cmd")
                .args(&["/C", "start", "msedge", &cmd_url]) // launch ms edge 
                .status();
        thread::sleep(Duration::from_secs(10));
    }

}

